$schema: "http://json-schema.org/draft-04/schema#"

id: "environmental_metadata"
title: Environmental Metadata (Metagenomics)
type: object
nodeTerms: null
namespace: https://nci-crdc-demo.datacommons.io/
category: biospecimen
program: '*'
project: '*'
description: Any material sample taken from a biological entity for testing, diagnostic, propagation, treatment or research purposes, including a sample obtained from a living organism or taken from the biological object after halting of all its life functions. Biospecimen can contain one or more components including but not limited to cellular molecules, cells, tissues, organs, body fluids, embryos, and body excretory products.
additionalProperties: false
submittable: true
validators: null

systemProperties:
  - id
  - project_id
  - state
  - created_datetime
  - updated_datetime

links:
  - name: experiments
    backref: environmentals
    label: derived_from
    target_type: experiment
    multiplicity: many_to_one
    required: true

required:
  - submitter_id
  - type
  - projects

uniqueKeys:
  - [id]
  - [project_id, submitter_id]

properties:

  $ref: "_definitions.yaml#/organism_properties"

  sample_title:
    description: The title of the sample
    type: string 

  projects:
    $ref: "_definitions.yaml#/to_many_project"

  host:
    type: [string, null]
    description: The natural (as opposed to laboratory) host to the organism from which the sample was obtained. Use the full taxonomic name, eg, "Homo sapiens".

  isolation_source: 
    type: [string, null]
    description: Describes the physical, environmental and/or local geographical source of the biological sample from which the sample was derived.

  collection_date:
    $ref: "_definitions.yaml#/datetime"

  rel_to_oxygen: 
    description: Aerobic or anaerobic
    default: aerobic
    enum:
      - aerobic 
      - anaerobic
